//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""FlappyFish"",
            ""id"": ""685feba7-85a6-459c-b35b-7546f406902e"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""e5b0284b-85c7-4168-99c2-980006880f22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fe17f2a0-75d3-4228-910c-138fb8877d65"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FlappyFish
        m_FlappyFish = asset.FindActionMap("FlappyFish", throwIfNotFound: true);
        m_FlappyFish_Jump = m_FlappyFish.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FlappyFish
    private readonly InputActionMap m_FlappyFish;
    private IFlappyFishActions m_FlappyFishActionsCallbackInterface;
    private readonly InputAction m_FlappyFish_Jump;
    public struct FlappyFishActions
    {
        private @InputActions m_Wrapper;
        public FlappyFishActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_FlappyFish_Jump;
        public InputActionMap Get() { return m_Wrapper.m_FlappyFish; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlappyFishActions set) { return set.Get(); }
        public void SetCallbacks(IFlappyFishActions instance)
        {
            if (m_Wrapper.m_FlappyFishActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_FlappyFishActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_FlappyFishActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_FlappyFishActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_FlappyFishActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public FlappyFishActions @FlappyFish => new FlappyFishActions(this);
    public interface IFlappyFishActions
    {
        void OnJump(InputAction.CallbackContext context);
    }
}
